// prettier-ignore
async function allACtion(jskey,searchText='iphone',step='',behaviorsId='',countryCode='US'){
	const ACTIONSJSON=`{"AGREEMENT":{"selector":"div.agreement-confirm.cookie-accept-btn","pageFinish":"false","slide":"false"},"CLICKAD":{"selector":"a.btn-gesture.btn-guide","pageFinish":"false","slide":"false"},"SEARCH":{"inputSelector":"div.search-area input","buttonSelector":"button.search-button","pageFinish":"false","slide":"false"},"SECONDPAGE":{"selector":"a.btn-gesture.second-page-card","pageFinish":"false","slide":"false"},"ASSOCIATIONSEARCH":{"selector":"div.associationsearch-card","pageFinish":"false","slide":"false"},"INTERSTITIAL":{"selector":"div.inter div.inter-main","pageFinish":true,"slide":false},"INTERSTITIALCLOSE":{"selector":"div.inter div.inter-close","pageFinish":false,"slide":false},"CHECKPAGE":{"pageFinish":"false","slide":"false"},"ADEFFECT":{"pageFinish":"false","slide":"false"}}`;
	const ADS_FORM_DATA_URL='https://adcenter.airmobyte.com/prod-api/common/getFormDataInfo?countryCode=';
	const ADS_FALLBACK_PERSON={firstName:'John',lastName:'Smith',name:'John Smith',email:'john.smith@example.com',phone:'2025550148',address:'100 Main Street',city:'New York',state:'NY',zip:'10001',postalCode:'10001',company:'Example Inc'};
	const ADS_FIELD_ALIASES={firstName:['first name','firstname','given name','名','名字'],lastName:['last name','lastname','surname','family name','姓'],name:['name','full name','your name','姓名'],email:['email','e-mail','mail','邮箱'],phone:['phone','mobile','tel','telephone','cell','手机号','电话'],address:['address','street','addr','地址'],city:['city','城市'],state:['state','province','region','州','省'],zip:['zip','zipcode','postal','postal code','postcode','邮编'],company:['company','organization','organisation','公司']};
	const ADS_CONVERSION_TARGETS=[{key:'form',selector:'form, input, textarea, select'},{key:'submit',selector:'button[type="submit"], input[type="submit"], button, .submit, .btn-submit, [class*="submit"], [id*="submit"]'},{key:'download',selector:'a[href*="download"], a[download], button[class*="download"], [class*="download"]'},{key:'phone',selector:'a[href^="tel:"], [class*="phone"], [id*="phone"]'},{key:'contact',selector:'a[href*="contact"], button[class*="contact"], [class*="contact"], [id*="contact"]'},{key:'register',selector:'a[href*="register"], button[class*="register"], [class*="register"], [id*="register"], [class*="signup"], [id*="signup"]'},{key:'quote',selector:'a[href*="quote"], button[class*="quote"], [class*="quote"], [id*="quote"]'},{key:'continue',selector:'button, a, [role="button"]'}];
	const CONTINUE_TEXT_RE=/continue|next|start|get started|learn more|submit|sign up|register|quote|contact|继续|下一步|提交|注册|获取报价|联系客服/i;
	function parseActionConfig(){try{const parsed=JSON.parse(ACTIONSJSON);return parsed&&typeof parsed==='object'?parsed:{}}catch(error){console.log('ACTIONSJSON parse error:',error);return{}}}
	function normalizeActionName(value){return String(value||'').trim().toUpperCase()}
	function normalizeText(value){return String(value||'').replace(/\s+/g,' ').trim().toLowerCase()}
	function randomItem(list){if(!Array.isArray(list)||list.length===0)return null;return list[Math.floor(Math.random()*list.length)]}
	function clamp(value,min,max){return Math.max(min,Math.min(max,value))}
	function safeBooleanLike(value){if(typeof value==='boolean')return value;if(value==='true')return true;if(value==='false')return false;return value||''}
	function isElement(value){return value&&value.nodeType===1}
	function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
	function getAdsFormDataUrl(currentCountryCode){return`${ADS_FORM_DATA_URL}${currentCountryCode||''}`}
	const ACTION_KEY=parseActionConfig();
	const context=createContext();
	function createContext(){const actionName=normalizeActionName(jskey);const actionConfig=ACTION_KEY[actionName]||{};return{actionName,actionConfig,nowStep:step||'{step}',searchText,behaviorsId,countryCode,slide:safeBooleanLike(actionConfig.slide),pageFinish:safeBooleanLike(actionConfig.pageFinish)}}
	function queryAll(selector,root){if(!selector)return[];try{return Array.from((root||document).querySelectorAll(selector)).filter(isElement)}catch(error){console.log('query selector error:',selector,error);return[]}}
	function getElementText(element){if(!isElement(element))return'';return[element.innerText,element.textContent,element.getAttribute('aria-label'),element.getAttribute('title'),element.getAttribute('placeholder'),element.getAttribute('value'),element.getAttribute('name'),element.getAttribute('id'),element.className].filter(Boolean).join(' ')}
	function getDocumentBounds(){const doc=document.documentElement;const body=document.body;return{width:Math.max(doc.scrollWidth,body?body.scrollWidth:0,window.innerWidth||0),height:Math.max(doc.scrollHeight,body?body.scrollHeight:0,window.innerHeight||0)}}
	function hasVisibleStyle(element){if(!isElement(element))return false;const style=window.getComputedStyle(element);if(!style)return false;return!(style.display==='none'||style.visibility==='hidden'||Number(style.opacity)===0||style.pointerEvents==='none')}
	function isElementInDocumentRange(element){if(!isElement(element))return false;const rect=element.getBoundingClientRect();const bounds=getDocumentBounds();const left=rect.left+window.scrollX;const top=rect.top+window.scrollY;const right=left+rect.width;const bottom=top+rect.height;return rect.width>0&&rect.height>0&&right>=0&&bottom>=0&&left<=bounds.width&&top<=bounds.height}
	function isElementVisible(element){if(!isElement(element))return false;if(!hasVisibleStyle(element))return false;if(!isElementInDocumentRange(element))return false;return true}
	function pointHitsElement(element,x,y){if(!isElement(element))return false;const hit=document.elementFromPoint(x,y);return hit===element||element.contains(hit)}
	function getCandidatePoints(element){const rect=element.getBoundingClientRect();const safeLeft=clamp(rect.left,0,window.innerWidth);const safeTop=clamp(rect.top,0,window.innerHeight);const safeRight=clamp(rect.right,0,window.innerWidth);const safeBottom=clamp(rect.bottom,0,window.innerHeight);const centerX=safeLeft+(safeRight-safeLeft)/2;const centerY=safeTop+(safeBottom-safeTop)/2;return[{x:centerX,y:centerY},{x:safeLeft+4,y:safeTop+4},{x:safeRight-4,y:safeTop+4},{x:safeLeft+4,y:safeBottom-4},{x:safeRight-4,y:safeBottom-4}].filter(point=>point.x>=0&&point.y>=0&&point.x<=window.innerWidth&&point.y<=window.innerHeight)}
	function findClickablePoint(element){if(!isElementVisible(element))return null;const points=getCandidatePoints(element);for(const point of points){if(pointHitsElement(element,point.x,point.y))return toPageCoordinate(point)}const rect=element.getBoundingClientRect();return toPageCoordinate({x:rect.left+rect.width/2,y:rect.top+rect.height/2})}
	function toPageCoordinate(point){return{x:Math.round(point.x+window.scrollX),y:Math.round(point.y+window.scrollY)}}
	function formatPointPosition(point){if(!point)return'';return`${point.x},${point.y}`}
	function getValidElementsWithPointBySelector(selector){return queryAll(selector).map(element=>({element,point:findClickablePoint(element)})).filter(item=>item.point)}
	function findTargetBySelector(selector){return randomItem(getValidElementsWithPointBySelector(selector))}
	function createTargetResult(key,target,extra){return Object.assign({key,position:target?formatPointPosition(target.point):'',nextStep:'',slide:context.slide,pageFinish:context.pageFinish},extra||{})}
	async function getAdEffectPerson(){try{const response=await fetch(getAdsFormDataUrl(context.countryCode),{method:'GET',credentials:'omit'});const result=await response.json();const data=result&&(result.data||result.result||result);if(data&&typeof data==='object')return Object.assign({},ADS_FALLBACK_PERSON,data)}catch(error){console.log('fetch ad effect person error:',error)}return Object.assign({},ADS_FALLBACK_PERSON)}
	function getFieldIdentity(element){if(!isElement(element))return'';const id=element.getAttribute('id')||'';const name=element.getAttribute('name')||'';const placeholder=element.getAttribute('placeholder')||'';const ariaLabel=element.getAttribute('aria-label')||'';const labelText=getRelatedLabelText(element);return normalizeText([id,name,placeholder,ariaLabel,labelText].join(' '))}
	function getRelatedLabelText(element){const id=element.getAttribute('id');const texts=[];if(id){const labels=queryAll(`label[for="${cssEscape(id)}"]`);labels.forEach(label=>texts.push(label.innerText||label.textContent||''))}const parentLabel=element.closest&&element.closest('label');if(parentLabel)texts.push(parentLabel.innerText||parentLabel.textContent||'');const wrapper=element.parentElement;if(wrapper){const labelLike=wrapper.querySelector('label');if(labelLike)texts.push(labelLike.innerText||labelLike.textContent||'')}return texts.filter(Boolean).join(' ')}
	function cssEscape(value){if(window.CSS&&typeof window.CSS.escape==='function')return window.CSS.escape(value);return String(value).replace(/"/g,'\\"')}
	function resolveFieldKey(element){const identity=getFieldIdentity(element);for(const key of Object.keys(ADS_FIELD_ALIASES)){const aliases=ADS_FIELD_ALIASES[key];if(aliases.some(alias=>identity.includes(normalizeText(alias))))return key}const type=normalizeText(element.getAttribute('type'));if(type==='email')return'email';if(type==='tel')return'phone';return''}
	function setNativeValue(element,value){const prototype=Object.getPrototypeOf(element);const descriptor=Object.getOwnPropertyDescriptor(prototype,'value');if(descriptor&&descriptor.set)descriptor.set.call(element,value);else element.value=value;element.dispatchEvent(new Event('input',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}))}
	function fillFormField(element,value){if(!isElement(element))return false;if(value===undefined||value===null||value==='')return false;const tagName=normalizeText(element.tagName);const type=normalizeText(element.getAttribute('type'));if(tagName==='select'){const options=Array.from(element.options||[]).filter(option=>!option.disabled&&option.value!=='');const option=options.find(item=>normalizeText(item.textContent).includes(normalizeText(value)))||options[0];if(!option)return false;element.value=option.value;element.dispatchEvent(new Event('change',{bubbles:true}));return true}if(type==='checkbox'||type==='radio'){element.checked=true;element.dispatchEvent(new Event('click',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}));return true}setNativeValue(element,String(value));return true}
	async function fillVisibleFormFields(person){const fields=queryAll('input, textarea, select').filter(isElementVisible).filter(element=>!element.disabled&&!element.readOnly);let filledCount=0;for(const field of fields){const key=resolveFieldKey(field);if(!key)continue;const value=person[key]||(key==='zip'?person.postalCode:'');if(fillFormField(field,value)){filledCount+=1;await sleep(40)}}return filledCount}
	function shouldBlockByInterstitial(){if(context.actionName==='INTERSTITIAL'||context.actionName==='INTERSTITIALCLOSE')return false;const interstitialConfig=ACTION_KEY.INTERSTITIAL||{};const closeConfig=ACTION_KEY.INTERSTITIALCLOSE||{};const interstitialTarget=findTargetBySelector(interstitialConfig.selector);const closeTarget=findTargetBySelector(closeConfig.selector);return!!interstitialTarget&&!closeTarget}
	function findConversionTarget(){for(const item of ADS_CONVERSION_TARGETS){const targets=getValidElementsWithPointBySelector(item.selector);if(item.key==='continue'){const matched=targets.find(target=>CONTINUE_TEXT_RE.test(getElementText(target.element)));if(matched)return{key:item.key,target:matched};continue}if(targets.length>0)return{key:item.key,target:randomItem(targets)}}return{key:'',target:null}}
	function findAvailableAction(){const priority=['AGREEMENT','CLICKAD','SEARCH','SECONDPAGE','ASSOCIATIONSEARCH','INTERSTITIALCLOSE'];for(const actionName of priority){const actionConfig=ACTION_KEY[actionName]||{};if(actionName==='SEARCH'){const inputTarget=findTargetBySelector(actionConfig.inputSelector);const buttonTarget=findTargetBySelector(actionConfig.buttonSelector);if(inputTarget||buttonTarget)return{key:'search',nextStep:inputTarget&&!buttonTarget?'{searchButton}':'',target:inputTarget||buttonTarget};continue}const target=findTargetBySelector(actionConfig.selector);if(target)return{key:actionName.toLowerCase(),nextStep:'',target}}const conversion=findConversionTarget();if(conversion.target)return{key:conversion.key,nextStep:'',target:conversion.target};return{key:'',nextStep:'',target:null}}
	async function handleAdEffectAction(){const person=await getAdEffectPerson();const filledCount=await fillVisibleFormFields(person);const conversion=findConversionTarget();return createTargetResult(conversion.key||'adeffect',conversion.target,{nextStep:filledCount>0?'{submit}':'',filledCount})}
	async function handleCheckPageAction(){const available=findAvailableAction();return createTargetResult(available.key||'checkpage',available.target,{nextStep:available.nextStep||''})}
	async function handleSearchAction(){const inputSelector=context.actionConfig.inputSelector;const buttonSelector=context.actionConfig.buttonSelector;if(context.nowStep==='{step}'){const inputTarget=findTargetBySelector(inputSelector);return createTargetResult('search',inputTarget,{nextStep:'{searchButton}'})}if(context.nowStep==='{searchButton}'){const inputTarget=findTargetBySelector(inputSelector);if(inputTarget&&inputTarget.element){fillFormField(inputTarget.element,context.searchText);await sleep(80)}const buttonTarget=findTargetBySelector(buttonSelector);return createTargetResult('search',buttonTarget)}const target=findTargetBySelector(buttonSelector)||findTargetBySelector(inputSelector);return createTargetResult('search',target)}
	async function handleDefaultClickAction(){const selector=context.actionConfig.selector;const target=findTargetBySelector(selector);return createTargetResult(context.actionName.toLowerCase(),target)}
	function getActionHandler(){const handlers={ADEFFECT:handleAdEffectAction,CHECKPAGE:handleCheckPageAction,SEARCH:handleSearchAction};return handlers[context.actionName]||handleDefaultClickAction}
	function reportActionResult(result){const payload=Object.assign({key:context.actionName.toLowerCase(),position:'',nextStep:'',slide:context.slide,pageFinish:context.pageFinish},result||{});console.log('payload==>',payload);JSBehavior.jsResult(payload.key||'',payload.position||'',payload.nextStep||'',payload.slide,payload.pageFinish,context.behaviorsId||'')}
	try{if(shouldBlockByInterstitial()){reportActionResult({key:context.actionName.toLowerCase(),position:'',nextStep:'irregularinter',slide:'',pageFinish:''});return}const handler=getActionHandler();const result=await handler();reportActionResult(result)}catch(error){console.log('allACtion error:',error);reportActionResult({key:context.actionName.toLowerCase(),position:'',nextStep:'',slide:context.slide,pageFinish:context.pageFinish})}
}
